const API="http://127.0.0.1:8765";let currentTab=null,watching=null;
async function getCurrentTab(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});currentTab=tabs[0]||null;tabTitle.textContent=currentTab?.title||"No active tab";tabUrl.textContent=currentTab?.url||"";}
async function request(path,options={}){const r=await fetch(API+path,options);const d=await r.json();if(!r.ok)throw new Error(d.error||"Lilly returned an error");return d;}async function post(path,payload={}){return request(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});}
async function refresh(){try{const d=await request("/health");watching=d.watching;connection.textContent=watching?"● Lilly connected — live monitor selected":"● Lilly connected";connection.className="status online";watch.disabled=false;capture.disabled=!watching;stop.disabled=!watching;livePrice.textContent=d.latest_price??"Waiting for TradingView…";renderTasks(d.tasks||[]);const s=await chrome.runtime.sendMessage({type:"LIVE_STATUS"});if(s?.lastPrice!=null)livePrice.textContent=s.lastPrice;liveHint.textContent=watching?"Updates are saved to Lilly history.":"Select a TradingView chart tab.";}catch(e){connection.textContent="● Lilly desktop app is not connected";connection.className="status offline";watch.disabled=capture.disabled=stop.disabled=true;}}
function renderTasks(items){if(!items.length){tasks.textContent="No tasks yet.";return;}tasks.innerHTML="";items.slice().reverse().forEach(t=>{const row=document.createElement("div");row.className="task"+(t.triggered?" triggered":"");const rel=t.kind==="price_above"?">=":"<=";row.append(document.createTextNode(`${t.label||"Price watch"}: ${rel} ${t.level} — ${t.triggered?"TRIGGERED":t.active?"ACTIVE":"INACTIVE"}`));const b=document.createElement("button");b.className="delete";b.textContent="Delete";b.onclick=async()=>{await request("/tasks/"+t.id,{method:"DELETE"});await refresh();};row.appendChild(b);tasks.appendChild(row);});}
watch.onclick=async()=>{try{if(!currentTab?.url?.includes("tradingview.com"))throw new Error("Automatic price monitoring currently supports TradingView chart tabs.");await post("/watch",{tab_id:currentTab.id,title:currentTab.title,url:currentTab.url});await chrome.runtime.sendMessage({type:"START_LIVE_MONITOR",tabId:currentTab.id});message.textContent="Live monitoring started.";await refresh();}catch(e){message.textContent=e.message;}};
stop.onclick=async()=>{try{await chrome.runtime.sendMessage({type:"STOP_LIVE_MONITOR"});await post("/stop");message.textContent="Live monitoring stopped.";await refresh();}catch(e){message.textContent=e.message;}};
capture.onclick=async()=>{try{if(currentTab.id!==watching?.tab_id)throw new Error("Open the watched tab before capturing.");const image_data=await chrome.tabs.captureVisibleTab(currentTab.windowId,{format:"jpeg",quality:85});await post("/capture",{tab_id:currentTab.id,title:currentTab.title,url:currentTab.url,image_data,width:screen.width,height:screen.height});message.textContent="Chart capture saved.";}catch(e){message.textContent=e.message;}};
addTask.onclick=async()=>{try{if(!level.value)throw new Error("Enter a price level.");await post("/tasks",{kind:kind.value,level:Number(level.value),label:label.value});level.value="";label.value="";message.textContent="Watch task added.";await refresh();}catch(e){message.textContent=e.message;}};
getUpdate.onclick=async()=>{try{const d=await request("/update"),u=d.update;updateBox.style.display="block";if(!u.count){updateText.textContent="No observations in the current session yet.";return;}const ch=u.change>=0?"+"+u.change.toFixed(2):u.change.toFixed(2);updateText.textContent=`Current session | Latest ${u.latest} | High ${u.high} | Low ${u.low} | Change ${ch} | ${u.count} observations | ${u.active_tasks} active task(s) | ${u.triggered_tasks} triggered this session`;}catch(e){message.textContent=e.message;}};
resetSession.onclick=async()=>{try{await post("/session/reset");updateBox.style.display="none";message.textContent="New monitoring session started. Old history was kept.";await refresh();}catch(e){message.textContent=e.message;}};
(async()=>{await getCurrentTab();await refresh();setInterval(refresh,2000);})();